### ISSUE TITLE
basic tests for server - can GET/PUSH, load index.html

### ISSUE THREAD

**Issue by alexnitta** [mediocreokra/amblr#24]

**Comment by alexnitta** [comment]
Set up Jasmine testing for calls to the API
1. When GET at root, response is 200
2. When POST at api/poi, response is 201
3. When POST at api/user, response is 201

**Comment by tobensg** [comment]
Basic tests are up.  Need to test POSTs still.
See test/test.js inside server and run tests with either grunt test or grunt simplemocha
